ESTATUS_ACTIVO          = "ACTIVO"
ESTATUS_VACANTE         = "VACANTE"
ESTATUS_VENCIDO         = "VENCIDO"
ESTATUS_POR_VENCER      = "POR VENCER"
PERSONAL_ACTIVO         = "ACTIVO"
PERSONAL_PASIVO         = "PASIVO"
ESTATUS_PERMITIDOS      = ["SUSPENDIDO", "BLOQUEADO", "ACTIVO"]
ESTATUS_PERMITIDOS_EGRESOS = ["PASIVO", "EGRESADO"]
